#=============================================================================
# init.toml --- My SpaceVim Config
# Author: Giseong Bak < giseong.bak at gmail.com >
#=============================================================================
#
# SpaceVim Options {{{
[options]
# General
    max_column = 120
    relativenumber = false
    filemanager = "nerdtree"
# Color
    enable_guicolors = true
    colorscheme_bg = "dark"
    colorscheme = "one"
# UI
    sidebar_width = 40
    terminal_cursor_shape = 1
    enable_tabline_filetype_icon = true
    enable_os_fileformat_icon = true
    enable_statusline_mode = true
    enable_vimfiler_filetypeicon = true
    enable_vimfiler_gitstatus = true
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    windows_index_type = 4
# Bootstrap
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"
# diable plugins
    disabled_plugins = ["srcery-vim"]
# }}}

# SpaceVim Layer Configs {{{
[[layers]]
    name = "ui"
[[layers]]
    name = "colorscheme"
[[layer]]
    name = "VersionControl"
[[layer]]
    name = "git"
[[layers]]
    name = "denite"
[[layers]]
    name = 'core#statusline'
    enable = true
[[layers]]
    name = 'core#tabline'
    enable = true
[[layer]]
    name = "incsearch"
[[layer]]
    name = "tools"
[[layer]]
    name = "sudo"
[[layer]]
    name = "format"
[[layers]]
    name = "shell"
    default_position = "top"
    default_height = 30
[[layers]]
    name = "autocomplete"
    auto-completion-return-key-behavior = "complete"
    auto-completion-tab-key-behavior = "smart"
[[layers]]
    name = "tmux"
[[layers]]
    name = "gtags"
    gtagslabel = "pygments"
[[layers]]
    name = "ldeaderf"

# Languages
[[layer]]
    name = "lang#c"
[[layer]]
    name = "lang#python"
[[layer]]
    name = "lang#javascript"
[[layer]]
    name = "lang#typescript"
[[layer]]
    name = "lang#vue"
[[layer]]
    name = "lang#markdown"
[[layer]]
    name = "lang#html"
[[layer]]
    name = "lang#vim"
[[layer]]
    name = "lang#sh"
[[layer]]
    name = "lang#json"
[[layer]]
    name = "lang#dockerfile"
[[layer]]
    name = "lang#plantmul"
[[layer]]
    name = "lang#extra"
# }}}

# Custom Plugins {{{
[[custom_plugins]]
    name = "chriskempson/base16-vim"
    merged = 0
[[custom_plugins]]
    name = 'lilydjwg/colorizer'
    merged = 0
    on_cmd = ['ColorHighlight']
[[custom_plugins]]
    name = 'kien/tabman.vim'
    merged = 0
[[custom_plugins]]
    name = 'tweekmonster/startuptime.vim'
    merged = 0
[[custom_plugins]]
    name = 'kergoth/vim-bitbake'
    merged = 0
# }}}
