#=============================================================================
# init.toml --- My SpaceVim Config
# Author: Giseong Bak < giseong.bak at gmail.com >
#=============================================================================
#
# SpaceVim Options {{{
[options]
# General
    max_column = 120
    relativenumber = false
    filemanager = "nerdtree"
# Color
    enable_guicolors = true
    colorscheme_bg = "dark"
    colorscheme = "catppuccin-mocha"
    custom_color_palette = [
      ["#1e1e2e", "#cba6f7", 183, 234],  # Normal mode: bg, fg
      ["#1e1e2e", "#f5e0dc", 223, 234],  # Insert mode: bg, fg
      ["#1e1e2e", "#f9e2af", 223, 234],  # Visual mode: bg, fg
      ["#6c7086", 60],                   # Inactive fg
      ["#1e1e2e", "#89b4fa", 234, 117],  # Info: bg, fg
      ["#1e1e2e", "#f38ba8", 234, 211],  # Warning: bg, fg
      ["#1e1e2e", "#a6e3a1", 234, 142],  # Error: bg, fg
      ["#1e1e2e", "#94e2d5", 234, 108],  # Success: bg, fg
      ["#1e1e2e", "#fab387", 234, 216]   # Command mode: bg, fg
    ]
# UI
    sidebar_width = 40
    terminal_cursor_shape = 1
    enable_tabline_filetype_icon = true
    enable_os_fileformat_icon = true
    enable_statusline_mode = true
    enable_vimfiler_filetypeicon = true
    enable_vimfiler_gitstatus = true
    statusline_separator = "curve"
    statusline_inactive_separator = "curve"
    buffer_index_type = 4
    windows_index_type = 4
# Bootstrap
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"
# diable plugins
    disabled_plugins = ["srcery-vim"]
# }}}

# SpaceVim Layer Configs {{{
[[layers]]
    name = "default"
[[layers]]
    name = "ui"
[[layers]]
    name = "colorscheme"
[[layer]]
    name = "VersionControl"
[[layer]]
    name = "git"
[[layers]]
    name = "denite"
[[layers]]
    name = 'core#statusline'
    enable = true
[[layers]]
    name = 'core#tabline'
    enable = true
[[layer]]
    name = "incsearch"
[[layer]]
    name = "tools"
[[layer]]
    name = "sudo"
[[layer]]
    name = "format"
[[layers]]
    name = "shell"
    default_position = "top"
    default_height = 30
[[layers]]
    name = "autocomplete"
    auto-completion-delay = 10
    auto-completion-return-key-behavior = "smart"
    auto-completion-tab-key-behavior = "smart"
[[layers]]
    name = "tmux"
[[layers]]
    name = "gtags"
    gtagslabel = "pygments"
[[layers]]
    name = "ldeaderf"

# Languages
[[layer]]
    name = "lang#c"
[[layer]]
    name = "lang#python"
[[layer]]
    name = "lang#javascript"
[[layer]]
    name = "lang#typescript"
[[layer]]
    name = "lang#markdown"
[[layer]]
    name = "lang#html"
[[layer]]
    name = "lang#vim"
[[layer]]
    name = "lang#sh"
[[layer]]
    name = "lang#json"
[[layer]]
    name = "lang#dockerfile"
[[layer]]
    name = "lang#plantmul"
[[layer]]
    name = "lang#extra"
# }}}

# Custom Plugins {{{
[[custom_plugins]]
    name = 'catppuccin/nvim'
    merged = 0
[[custom_plugins]]
    name = 'lilydjwg/colorizer'
    merged = 0
    on_cmd = ['ColorHighlight']
[[custom_plugins]]
    name = 'kien/tabman.vim'
    merged = 0
# }}}
