#=============================================================================
# init.toml --- My SpaceVim Config
# Author: Giseong Bak < giseong.bak at gmail.com >
#=============================================================================
#
# SpaceVim Options {{{
[options]
# General
    max_column = 120
    relativenumber = false
# Color
    enable_guicolors = false
    colorscheme_bg = "dark"
    colorscheme = "base16-default-dark"
#UI
    sidebar_width = 40
    terminal_cursor_shape = 1
    enable_tabline_filetype_icon = true
    enable_os_fileformat_icon = true
    enable_statusline_mode = true
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
# }}}

# SpaceVim Layer Configs {{{
[[layers]]
    name = "default"
[[layers]]
    name = "colorscheme"
[[layer]]
    name = "VersionControl"
[[layers]]
    name = "shell"
    default_position = "top"
    default_height = 30
[[layers]]
    name = "denite"
[[layers]]
    name = "autocomplete"
    auto-completion-return-key-behavior = "complete"
    auto-completion-tab-key-behavior = "smart"
[[layers]]
    name = "tmux"
[[layers]]
    name = "tags"
# Languages
[[layer]]
    name = "lang#c"
[[layer]]
    name = "lang#python"
[[layer]]
    name = "lang#markdown"
[[layer]]
    name = "lang#vim"
[[layer]]
    name = "lang#tmux"
[[layer]]
    name = "lang#toml"
# }}}

# Custom Plugins {{{
[[custom_plugins]]
    name = "chriskempson/base16-vim"
    merged = 0
# }}}
